// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/06/2024 12:04:48
const configMerger = require("C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/plugins/**/*.{js,ts,mjs}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/composables/**/*.{js,ts,mjs}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/utils/**/*.{js,ts,mjs}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/kolade.aboudou/Desktop/devoir_tiburce/kolade.urlshortener.com/formkit.theme.ts";;return cfg;})()
